import Head from 'next/head'
import Header from './header'
import Image from 'next/image'

export default function Layout(props:any) {
  return (
    <div  dir="rtl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/bootstrap/dist/css/bootstrap.rtl.min.css" />
        <link rel="stylesheet" href="/shabnam-font/dist/font-face.css" />
      </Head>

        <Header></Header>

      <main className={"container main"}>
          {props.children}
          <footer className="p-4 px-3 my-md-5 pt-md-5 border-top">
              <div className="row">
                  <div className="col-12 col-md">
                      <h2>تکستینو</h2>
                      <small className="d-block mb-3 text-muted">© 2017–2021</small>
                  </div>
                  <div className="col-6 col-md">
                      <h5>مقالات</h5>
                      <ul className="list-unstyled text-small">
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">برنامه نویسی</a>
                          </li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">آشپری</a></li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">تدریس</a></li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">اهنگسازی</a>
                          </li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">خوانندگی</a></li>
                      </ul>
                  </div>
                  <div className="col-6 col-md">
                      <h5>دوره ها</h5>
                      <ul className="list-unstyled text-small">
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">برنامه نویسی</a>
                          </li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">آشپری</a></li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">نجاری</a></li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">تدریس</a></li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">اهنگسازی</a>
                          </li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">خوانندگی</a></li>
                      </ul>
                  </div>
                  <div className="col-6 col-md">
                      <h5>دسترسی</h5>
                      <ul className="list-unstyled text-small">
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">برنامه نویسی</a>
                          </li>
                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">آشپری</a></li>

                          <li className="mb-1"><a className="link-secondary text-decoration-none" href="#">خوانندگی</a></li>
                      </ul>
                  </div>
              </div>
          </footer>
      </main>

        <script  src="/bootstrap/dist/js/bootstrap.min.js" ></script>
    </div>
  )
}
